[features]
seeds = false
skip-lint = false

[programs.localnet]
defi_trust_fund = "YourProgramIdHere1111111111111111111111111111"

[programs.devnet]
defi_trust_fund = "YourProgramIdHere1111111111111111111111111111"

[programs.mainnet]
defi_trust_fund = "YourProgramIdHere1111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

